Repository IgniteUI/help-topics, pull requests merged in 2018-08, with the labels that each got.

#392 Replaced the deprecated jQuery "delegate" method with "on"
  topics/02_Controls/igGrid/03_Features/02_Row Selectors/02_igGrid_RowSelectors_Events.md
Labels: 17.2

#393 Replaced the deprecated jQuery "delegate" method with "on"
  topics/02_Controls/igGrid/03_Features/02_Row Selectors/02_igGrid_RowSelectors_Events.md
Labels: 18.1

#395 Changing "Angular 2" to "Angular" in Getting Started topic
  topics/01_General-and-Getting-Started/~Getting_Started.md
Labels: 17.2, bug

#394 Changing "Angular 2" to "Angular" in Getting Started topic
  topics/01_General-and-Getting-Started/~Getting_Started.md
Labels: 18.1, bug
